[package]
name = "achilles"
version = "0.1.0"
edition = "2021"

[dependencies]
nes-types = {path = "../nes-types"}
nes-rust-client = {path = "../nes-rust-client"}
log = "0.4.21"
simple_logger = "5.0.0"
tokio = "1.38.0"
csv = "1.3.0"
rand = "0.8.5"
yaml-rust2 = "0.8.1"
ron = "0.8"
clap = "4.5.13"

